drop table if exists ZZ;
drop table if exists YY;
drop table if exists XX;
drop table if exists WW;
drop table if exists VV;
drop table if exists UU;
drop table if exists TT;
drop table if exists QQ;
drop table if exists PP;
